[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.gd", "php82Extensions.bcmath", "php82Extensions.tokenizer", "php82Extensions.ctype", "php82Extensions.fileinfo", "composer", "nodejs_20", "npm-9_x"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-zip", "npm install", "npm run build"]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"